### ISSUE TITLE
Mock SQL Server - JAVA-Mock Comm

### ISSUE THREAD

**Issue by johnpaulkee** [UBC-CPSC319/team-7#17]
DTO DOW etc. work.

Heroku working with SQL on deployment server.

**Comment by johnpaulkee** [comment]
ideally gerrit -> heroku -> Github

**Comment by johnpaulkee** [comment]
Postgres solution works, many dependencies for migration with Coast later on. Free solutions include:
Microsoft SQL Server Express (Allows only limited amounts of data)
How do we host it?
- We get $25 for hosting it on Azure

**Comment by johnpaulkee** [comment]
Use Azure DB <-> Java Server

**Comment by andrewbatesubc** [comment]
Azure hosting up and running, and Java is connecting and retrieving rows.
